### ISSUE TITLE
Remove OPT models

### ISSUE THREAD

**Issue by ArthurConmy** [callummcdougall/SERI-MATS-2023-Streamlit-pages#2]
I think there are 3 files where we do this:

![image](https://github.com/callummcdougall/SERI-MATS-2023-Streamlit-pages/assets/35957051/ca3e3ec4-7cf3-4e7b-859d-ae5b974a9095)

**Comment by callummcdougall** [comment]
Oh yeah, I was just basing that on this (from TL model properties table), didn't question ot at the time
![image](https://github.com/callummcdougall/SERI-MATS-2023-Streamlit-pages/assets/45238458/f45de6c3-fe8b-468d-bf90-9b2c0247f5b4)

**Comment by ArthurConmy** [comment]
I'd recommend also looking at some Pythia models too? 

Getting mechanistic may be harder, but since we don't expect copy suppression to care about positions I think this would provide some signal (+ there are loads of pythia models)

**Comment by ArthurConmy** [comment]
The new plot fixes this
